name: Build .so

on:
  push:
    branches: "master"
  pull_request:
    branches: "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      #- name: Set up Android SDK
        #uses: android-actions/setup-android@v3

      #- name: Install NDK 27.1.12297006 and cmake
        #run: |
          #sdkmanager "ndk;27.1.12297006" "cmake;3.30.5"
          
      - name: Grant execute permission for gradlew
        run: chmod +x BNMExplorerDEBUG/gradlew

      - name: Build release
        run: |
          cd BNMExplorerDEBUG
          ./gradlew assembleRelease

      - name: Find .so file from build
        run: |
          cd BNMExplorerDEBUG
          find . -name "*.so" | grep -v ".gradle" | sort

      - name: Upload .so artifact
        uses: actions/upload-artifact@v4
        with:
          name: libBNMExp-arm64
          path: BNMExplorerDEBUG/app/build/intermediates/stripped_native_libs/*/*/*/*/*.so
